[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:mysql]
command=/usr/bin/mysqld_safe --user=mysql
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/mysql_err.log
stdout_logfile=/var/log/supervisor/mysql_out.log
priority=10

[program:apache2]
command=/bin/bash -c "source /etc/apache2/envvars && exec /usr/sbin/apache2 -D FOREGROUND"
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/apache_err.log
stdout_logfile=/var/log/supervisor/apache_out.log
priority=20
